bla

diff --git a/contrib/fonts/make_emojis b/contrib/fonts/make_emojis
--- a/contrib/fonts/make_emojis
+++ b/contrib/fonts/make_emojis
@@ -25,13 +25,8 @@
 
 set -e
 
-if [ `uname` == "Darwin" ]; then
-	realpath=grealpath
-else
-	realpath=realpath
-fi
-
-here=$(dirname $($realpath "$0"))
+here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
+test -n "$here" -a -d "$here" || (echo "Cannot determine build dir. FIXME!" && exit 1)
 . "$here"/../base.sh # functions we use below (fail, et al)
 
 SRCURL="https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip"
